[init_hosts]
prd-hs-launchpad001.hlc.homelab6.com
prd-hs-compute001.hlc.homelab6.com
prd-hs-host001.hlc.homelab6.com
prd-vm-dockeradmin001.hlc.homelab6.com
dev-vm-almalinuxhvm.hlc.homelab6.com
dev-vm-almalinux.hlc.homelab6.com
dev-vm-develop001.hlc.homelab6.com
dev-vm-test001.hlc.homelab6.com

[all]
dsk-hs-macmini001.dsk.homelab6.com
prd-hs-compute001.hlc.homelab6.com
prd-hs-host001.hlc.homelab6.com
prd-hs-launchpad001.hlc.homelab6.com
dev-vm-almalinuxgpu.hlc.homelab6.com
dev-vm-almalinuxhvm.hlc.homelab6.com
dev-vm-almalinuxpv.hlc.homelab6.com
dev-vm-nvidia.hlc.homelab6.com
dev-vm-nvidiallm.hlc.homelab6.com
dev-vm-nvidiapv.hlc.homelab6.com
prd-vm-ansible001.hlc.homelab6.com
prd-vm-checkupdate001.hlc.homelab6.com
prd-vm-buildkit001.hlc.homelab6.com
prd-vm-buildimage001.hlc.homelab6.com
prd-vm-registry001.hlc.homelab6.com
prd-vm-repository001.hlc.homelab6.com
prd-vm-dockeradmin001.hlc.homelab6.com
prd-vm-dockeradmin002.hlc.homelab6.com
prd-vm-dockeradmin003.hlc.homelab6.com
prd-vm-dockeradmin004.hlc.homelab6.com
prd-vm-dockeradmin005.hlc.homelab6.com
prd-vm-shield001.hlc.homelab6.com
prd-vm-shield002.hlc.homelab6.com
prd-vm-shield003.hlc.homelab6.com
prd-vm-pfsense001.hlc.homelab6.com
prd-vm-compute001.hlc.homelab6.com
prd-vm-compute002.hlc.homelab6.com
prd-vm-compute003.hlc.homelab6.com
prd-vm-compute004.hlc.homelab6.com
prd-vm-compute005.hlc.homelab6.com
prd-vm-compute006.hlc.homelab6.com
prd-vm-blocksys001.hlc.homelab6.com
prd-vm-blocksys002.hlc.homelab6.com

[macmini]
dsk-hs-macmini001.dsk.homelab6.com

[hs]
prd-hs-compute001.hlc.homelab6.com
prd-hs-host001.hlc.homelab6.com
prd-hs-launchpad001.hlc.homelab6.com

[prd_hs]
prd-hs-compute001.hlc.homelab6.com
prd-hs-host001.hlc.homelab6.com
prd-hs-launchpad001.hlc.homelab6.com

[vm]
dev-vm-almalinuxgpu.hlc.homelab6.com
dev-vm-almalinuxhvm.hlc.homelab6.com
dev-vm-almalinuxpv.hlc.homelab6.com
dev-vm-nvidia.hlc.homelab6.com
dev-vm-nvidiallm.hlc.homelab6.com
dev-vm-nvidiapv.hlc.homelab6.com
prd-vm-ansible001.hlc.homelab6.com
prd-vm-checkupdate001.hlc.homelab6.com
prd-vm-buildkit001.hlc.homelab6.com
prd-vm-buildimage001.hlc.homelab6.com
prd-vm-registry001.hlc.homelab6.com
prd-vm-repository001.hlc.homelab6.com
prd-vm-dockeradmin001.hlc.homelab6.com
prd-vm-dockeradmin002.hlc.homelab6.com
prd-vm-dockeradmin003.hlc.homelab6.com
prd-vm-dockeradmin004.hlc.homelab6.com
prd-vm-dockeradmin005.hlc.homelab6.com
prd-vm-shield001.hlc.homelab6.com
prd-vm-shield002.hlc.homelab6.com
prd-vm-shield003.hlc.homelab6.com
prd-vm-pfsense001.hlc.homelab6.com
prd-vm-compute001.hlc.homelab6.com
prd-vm-compute002.hlc.homelab6.com
prd-vm-compute003.hlc.homelab6.com
prd-vm-compute004.hlc.homelab6.com
prd-vm-compute005.hlc.homelab6.com
prd-vm-compute006.hlc.homelab6.com
prd-vm-blocksys001.hlc.homelab6.com
prd-vm-blocksys002.hlc.homelab6.com

[dev_vm]
dev-vm-almalinuxgpu.hlc.homelab6.com
dev-vm-almalinuxhvm.hlc.homelab6.com
dev-vm-almalinuxpv.hlc.homelab6.com
dev-vm-nvidia.hlc.homelab6.com
dev-vm-nvidiallm.hlc.homelab6.com
dev-vm-nvidiapv.hlc.homelab6.com

[prd_vm]
prd-vm-ansible001.hlc.homelab6.com
prd-vm-checkupdate001.hlc.homelab6.com
prd-vm-buildkit001.hlc.homelab6.com
prd-vm-buildimage001.hlc.homelab6.com
prd-vm-registry001.hlc.homelab6.com
prd-vm-repository001.hlc.homelab6.com
prd-vm-dockeradmin001.hlc.homelab6.com
prd-vm-dockeradmin002.hlc.homelab6.com
prd-vm-dockeradmin003.hlc.homelab6.com
prd-vm-dockeradmin004.hlc.homelab6.com
prd-vm-dockeradmin005.hlc.homelab6.com
prd-vm-shield001.hlc.homelab6.com
prd-vm-shield002.hlc.homelab6.com
prd-vm-shield003.hlc.homelab6.com
prd-vm-pfsense001.hlc.homelab6.com
prd-vm-compute001.hlc.homelab6.com
prd-vm-compute002.hlc.homelab6.com
prd-vm-compute003.hlc.homelab6.com
prd-vm-compute004.hlc.homelab6.com
prd-vm-compute005.hlc.homelab6.com
prd-vm-compute006.hlc.homelab6.com
prd-vm-blocksys001.hlc.homelab6.com
prd-vm-blocksys002.hlc.homelab6.com

[prd_ansible]
prd-vm-ansible001.hlc.homelab6.com

[prd_checkupdate]
prd-vm-checkupdate001.hlc.homelab6.com

[prd_dockeradmin]
prd-vm-dockeradmin001.hlc.homelab6.com
prd-vm-dockeradmin002.hlc.homelab6.com
prd-vm-dockeradmin003.hlc.homelab6.com
prd-vm-dockeradmin004.hlc.homelab6.com
prd-vm-dockeradmin005.hlc.homelab6.com

[prd_shield]
prd-vm-shield001.hlc.homelab6.com
prd-vm-shield002.hlc.homelab6.com
prd-vm-shield003.hlc.homelab6.com

[prd_vm_compute]
prd-vm-compute001.hlc.homelab6.com
prd-vm-compute002.hlc.homelab6.com
prd-vm-compute003.hlc.homelab6.com
prd-vm-compute004.hlc.homelab6.com
prd-vm-compute005.hlc.homelab6.com
prd-vm-compute006.hlc.homelab6.com


[blocksys]
prd-vm-blocksys001.hlc.homelab6.com
prd-vm-blocksys002.hlc.homelab6.com
